primary:
  persistence:
    enabled: false
  service:
    port: 5432
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

auth:
  postgresPassword: password
  database: db
