apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-deploy
  template:
    metadata:
      labels:
        app: auth-deploy
    spec:
      containers:
      - name: auth-deploy
        image: stepigor/ot8auth:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: DB_PORT
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: APP_PORT
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: JWT_SECRET
        - name: DB_PSWD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: POSTGRES_PASSWORD
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: RABBITMQ_USER
        - name: RABBITMQ_PASS
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: RABBITMQ_PASS